# Generated by Django 5.2.8 on 2025-11-11 03:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0002_alter_cliente_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='data_fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='license',
            name='data_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
