# Generated by Django 5.2.1 on 2025-11-11 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0003_license_data_fim_license_data_inicio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='license',
            options={'ordering': ['-data_inicio'], 'verbose_name': 'Licença', 'verbose_name_plural': 'Licenças'},
        ),
    ]
